#Secrets are handled by Figaro gem

development:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  px_consumer_key: <%= Figaro.env.px_consumer_key %>

test:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  px_consumer_key: <%= Figaro.env.px_consumer_key %>

production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  px_consumer_key: <%= Figaro.env.px_consumer_key %>