# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d7b9d4bcf953d440de82b0f8eb35e4972817890e2a2aa0f05ea0052ddc33894676a0c649ad7a701158c2e85466cb78ab41c7e25a5add864ae42a2e41b16f563
  px_consumer_key: qQkbYn1PzNr887wsSCqNn0zXMpj2kpbEISOwwDr7
test:
  secret_key_base: 731e4c3f31b94ae0060f877c6dd85c00c7bce2003c624927a8da30391e178347498e63e240e03c4f327536dd1621ec1c058de4d9df17ee0bb2691b28a7ad2400

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
